twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        logo_file: '%env(LOGO_FILE)%'
        users_admin: '%env(USERS_ADMIN)%'
        users_manager: '%env(USERS_MANAGER)%'
        users_it: '%env(USERS_IT)%'
        users_ufficio_personale: '%env(USERS_UFFICIO_PERSONALE)%'
        users_newaccount_admin: '%env(USERS_NEWACCOUNT_ADMIN)%'
